### ISSUE TITLE
Some keys are not appearing

### ISSUE THREAD

**Issue by tristanbes** [erikdubbelboer/phpRedisAdmin#110]
Hello,

When showing `KEYS *` from redis-cli it outputs 4 keys:
<img width="1211" alt="_workspace_st" src="https://cloud.githubusercontent.com/assets/346010/26349249/79201fec-3faf-11e7-9710-ec417ee6bd02.png">

Yet, in the interface, we can only see 2 keys in the tree, yet, Redis information shows 4 keys:
<img width="603" alt="127_0_0_1_-_phpredisadmin" src="https://cloud.githubusercontent.com/assets/346010/26349142/39fe2a16-3faf-11e7-89c5-e49c2ba5ba06.png">

I've browsed all "databases" but the 2 missing keys aren't showing up. Am I missing something ?
Thanks.

**Comment by tristanbes** [comment]
Ok, figured it out:
`ERROR: Your key is to long (max length is 100)` 
Yet in Redis, there's a limit, but it's way higher than 100. Why did you limit keys to 100 char in the webinterface ?

**Comment by erikdubbelboer** [comment]
You can configure this at: https://github.com/erikdubbelboer/phpRedisAdmin/blob/52ee23a96b087f330cccc2950b76475b7e1ab97a/includes/config.sample.inc.php#L72

This was done because viewing keys uses HTTP GET with the key in the URL and some browsers don't support too long keys. Another reason is to prevent possible abuse.
