### ISSUE TITLE
ACL Support?

### ISSUE THREAD

**Issue by bl3nd3r** [erikdubbelboer/phpRedisAdmin#168]
Hi,

Are there any plans to support Redis ACLs? Assuming they're not supported already..

**Comment by erikdubbelboer** [comment]
You mean the ability to modify ACLs using the interface?

If so, that sounds like a good idea. But I'm afraid I don't have time to work on this now. Pull requests are always welcome of course!

**Comment by tricoos** [comment]
He is talking about using ACLs at all I assume because that does not work at all at the moment.
With ACLs you have a username and a password. However, phpRedisAdmin only uses the password thus it is impossible to use ACLs at the moment. Even if I set the password for the default user explicitly as ACL in Redis and provide the password in phpRedisAdmin it does not work at all.

It looks like phpRedisAdmin only works if ACLs are not used on the Redis server at all.
