### ISSUE TITLE
Multiple PHP Warnings in Docker for erikdubbelboer/phpredisadmin:1.21

### ISSUE THREAD

**Issue by DYFeng** [erikdubbelboer/phpRedisAdmin#214]
```
Deprecated: Predis\Client::createPipeline(): Implicitly marking parameter $options as nullable is deprecated, the explicit nullable type must be used instead in /src/app/vendor/predis/predis/src/Client.php on line 429

Deprecated: Predis\Client::createTransaction(): Implicitly marking parameter $options as nullable is deprecated, the explicit nullable type must be used instead in /src/app/vendor/predis/predis/src/Client.php on line 472

Deprecated: Predis\Client::createPubSub(): Implicitly marking parameter $options as nullable is deprecated, the explicit nullable type must be used instead in /src/app/vendor/predis/predis/src/Client.php on line 504

Deprecated: Predis\Profile\RedisProfile::setProcessor(): Implicitly marking parameter $processor as nullable is deprecated, the explicit nullable type must be used instead in /src/app/vendor/predis/predis/src/Profile/RedisProfile.php on line 124

Warning: Cannot modify header information - headers already sent by (output started at /src/app/vendor/predis/predis/src/Client.php:429) in /src/app/includes/header.inc.php on line 5

Warning: Cannot modify header information - headers already sent by (output started at /src/app/vendor/predis/predis/src/Client.php:429) in /src/app/includes/header.inc.php on line 6

Warning: Cannot modify header information - headers already sent by (output started at /src/app/vendor/predis/predis/src/Client.php:429) in /src/app/includes/header.inc.php on line 7
```

**Comment by longgt** [comment]
This issue might occur from tag 1.22 (PHP 8.4), not 1.21 (PHP 8.3)
The root cause is **phpRedisAdmin** image is built based on `composer:2.2` (which internally uses the latest version of PHP - 8.4)
https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/Dockerfile#L1

The version of PHP can be confirmed via env `PHP_VERSION`
https://hub.docker.com/layers/erikdubbelboer/phpredisadmin/latest/images/sha256-2d1ba8df89d780b0b2ea03336949604936011ca4cf5267c3ef02b16970ea3647

In composer.json, the version of library **predis/predis** is v1.1.9
https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/composer.json#L18

The warning issues above was fixed at `predis/predis:2.23.0`
https://github.com/predis/predis/blob/v2.x/CHANGELOG.md#v230-2024-11-21

**Comment by erikdubbelboer** [comment]
Did you test and confirm that everything works fine with `predis/predis:2.23.0`? If so I can update to that version in the composer.json.

**Comment by longgt** [comment]
I didn't test all cases but the below is what I tried with `redis:7.4.1`

(1) Start docker container with latest image
`erikdubbelboer/phpredisadmin:latest`
(2) Open admin page
Browse to http://localhost/
===> The warning above was shown.
(3) At docker container, install the latest version of `predis/predis`
`composer require predis/predis:v2.3.0`
===> Restart container
(4) Refresh admin page
===> The warning above was not shown anymore.
Some basic functions such as: change database, filter by key, delete the existing value seemed to be fine...
