### ISSUE TITLE
phpRedisAdmin

### ISSUE THREAD

**Issue by szepeviktor** [erikdubbelboer/phpRedisAdmin#86]
Very useful project.
Thank you!

**Comment by szepeviktor** [comment]
Is there a way to reload the "Keys" tree without the browser's Reload button?

**Comment by szepeviktor** [comment]
Pressing the [ Filter ] button?

**Comment by erikdubbelboer** [comment]
I'm afraid this is not possible at the moment. I'm guessing you don't want to reload the view you have on the right. The issue is that this view is embedded as iframe in the main page which contains the Keys. There is no ajax mechanism to refresh the Keys so refreshing the page with them will also reload the iframe.

**Comment by szepeviktor** [comment]
OK. Reload is fine for me.

Thank you once again.
